name: rpi_gpsd_chrony
services:
    rpi-gpsd:
        stdin_open: true
        tty: true
        devices:
            - /dev/ttyAMA0
            - /dev/pps0
        ports:
            - 123:123
        container_name: gpsd-chrony
        cap_add:
            - SYS_TIME
        privileged: true
        image: dkaulukukui/rpi-docker-gpsd-chrony
        volumes:
            - chrony_logs:/var/log/chrony
            - chrony_drift:/var/lib/chrony
            - ./chrony_config:/etc/chrony

volumes:
    chrony_logs:

    chrony_drift:
