name: rpi_gpsd_chrony
services:
    rpi-gpsd:
        stdin_open: true
        tty: true
        devices:
            - /dev/ttyAMA0
            - /dev/pps0
        ports:
            - 2948:2947
            - 123:123
        container_name: gpsd
        privileged: true
        image: rpi-gpsd
