name: Build & Push Docker Image

on:
  push:
    branches: [ "build_release" ]
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: buildx-action
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build_push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }},
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
